# Generated by Django 3.2.25 on 2025-07-08 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CampusConnectApp', '0002_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='notify_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='notify_staff',
            field=models.BooleanField(default=False),
        ),
    ]
