# Generated by Django 3.2.25 on 2025-07-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusConnectApp', '0003_auto_20250708_2216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasksubmission',
            unique_together={('task', 'student')},
        ),
    ]
